In [1]:
import pandas as pd
cuisines_df = pd.read_csv("C:/Users/jsand/OneDrive - OsloMet/NETTSKY/JOBB/IT/prosjekter/Microsoft-ML-Course/Classification/Data/cleaned_cuisines_R.csv")
cuisines_df.head()

,cuisine,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,indian,0.0,0,0.0,0.0,0.0,0,0.0,0,0,...,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
1,indian,1.0,0,0.0,0.0,0.0,0,0.0,0,0,...,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
2,indian,0.0,0,0.0,0.0,0.0,0,0.0,0,0,...,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
3,indian,0.0,0,0.0,0.0,0.0,0,0.0,0,0,...,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
4,indian,0.0,0,0.0,0.0,0.0,0,0.0,0,0,...,0,0.0,0.0,0.0,0.0,0,0.0,0.0,1.0,0.0

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report, precision_recall_curve
from sklearn.svm import SVC
import numpy as np

In [3]:
cuisines_label_df = cuisines_df['cuisine']
cuisines_label_df.head()

0    indian
1    indian
2    indian
3    indian
4    indian
Name: cuisine, dtype: object

In [4]:
cuisines_feature_df = cuisines_df.drop(['cuisine'], axis=1)
cuisines_feature_df.head()

,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,artichoke,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0.0,0,0.0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
1,1.0,0,0.0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
2,0.0,0,0.0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
3,0.0,0,0.0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
4,0.0,0,0.0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0.0,0.0,0,0.0,0.0,1.0,0.0

In [5]:
X_train, X_test, y_train, y_test = train_test_split(cuisines_feature_df, cuisines_label_df, test_size=0.3)

In [6]:
lr = LogisticRegression(solver="lbfgs")
model = lr.fit(X_train, np.ravel(y_train))

accuracy = model.score(X_test, y_test)
print ("Accuracy is {}".format(accuracy))

Accuracy is 0.8281901584653878

In [7]:
print(f'ingredients: {X_test.iloc[50][X_test.iloc[50]!=0].keys()}')
print(f'cuisine: {y_test.iloc[50]}')

ingredients: Index(['bean', 'lettuce', 'mushroom', 'oyster', 'peanut', 'soy_sauce',
       'soybean', 'wine'],
      dtype='object')
cuisine: chinese

In [8]:
test= X_test.iloc[50].values.reshape(-1, 1).T
proba = model.predict_proba(test)
classes = model.classes_
resultdf = pd.DataFrame(data=proba, columns=classes)

topPrediction = resultdf.T.sort_values(by=[0], ascending = [False])
topPrediction.head()

c:\Users\jsand\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

                 0
chinese   0.737030
thai      0.213480
korean    0.025448
japanese  0.023869
indian    0.000172

In [9]:
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

     chinese       0.78      0.75      0.77       251
      indian       0.94      0.94      0.94       252
    japanese       0.79      0.79      0.79       235
      korean       0.76      0.78      0.77       233
        thai       0.86      0.89      0.87       228

    accuracy                           0.83      1199
   macro avg       0.83      0.83      0.83      1199
weighted avg       0.83      0.83      0.83      1199

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier

In [11]:
X_train, X_test, y_train, y_test = train_test_split(cuisines_feature_df, cuisines_label_df, test_size=0.3)

In [20]:
C = 10
# Create different classifiers.
classifiers = {
    'Linear SVC': SVC(kernel='linear', C=C, probability=True,random_state=0),
    'KNN classifier': KNeighborsClassifier(C),
    'SVC': SVC(),
    'RFST': RandomForestClassifier(n_estimators=100),
    'ADA': AdaBoostClassifier(n_estimators=100)
}

In [21]:
n_classifiers = len(classifiers)

for index, (name, classifier) in enumerate(classifiers.items()):
    classifier.fit(X_train, np.ravel(y_train))

    y_pred = classifier.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy (train) for %s: %0.1f%% " % (name, accuracy * 100))
    print(classification_report(y_test,y_pred))

Accuracy (train) for Linear SVC: 86.2%
              precision    recall  f1-score   support

     chinese       0.83      0.84      0.84       258
      indian       0.93      0.92      0.92       229
    japanese       0.84      0.87      0.85       243
      korean       0.87      0.75      0.81       232
        thai       0.86      0.93      0.89       237

    accuracy                           0.86      1199
   macro avg       0.86      0.86      0.86      1199
weighted avg       0.86      0.86      0.86      1199

Accuracy (train) for KNN classifier: 78.0%
              precision    recall  f1-score   support

     chinese       0.71      0.74      0.72       258
      indian       0.84      0.84      0.84       229
    japanese       0.70      0.87      0.78       243
      korean       0.91      0.60      0.72       232
        thai       0.82      0.85      0.84       237

    accuracy                           0.78      1199
   macro avg       0.80      0.78      0.78      1199
weighted avg       0.79      0.78      0.78      1199

Accuracy (train) for SVC: 89.7%
              precision    recall  f1-score   support

     chinese       0.84      0.88      0.86       258
      indian       0.93      0.97      0.95       229
    japanese       0.88      0.91      0.89       243
      korean       0.94      0.79      0.86       232
        thai       0.91      0.95      0.93       237

    accuracy                           0.90      1199
   macro avg       0.90      0.90      0.90      1199
weighted avg       0.90      0.90      0.90      1199

Accuracy (train) for RFST: 89.7%
              precision    recall  f1-score   support

     chinese       0.88      0.83      0.86       258
      indian       0.92      0.96      0.94       229
    japanese       0.90      0.90      0.90       243
      korean       0.87      0.86      0.87       232
        thai       0.90      0.94      0.92       237

    accuracy                           0.90      1199
   macro avg       0.90      0.90      0.90      1199
weighted avg       0.90      0.90      0.90      1199

Accuracy (train) for ADA: 75.2%
              precision    recall  f1-score   support

     chinese       0.74      0.62      0.68       258
      indian       0.90      0.84      0.87       229
    japanese       0.61      0.82      0.70       243
      korean       0.77      0.71      0.74       232
        thai       0.83      0.78      0.80       237

    accuracy                           0.75      1199
   macro avg       0.77      0.75      0.76      1199
weighted avg       0.77      0.75      0.75      1199